"use client";

import { PROVIDER_LABELS, type ProviderId } from "@/lib/types";

export type Phase = "idle" | "generating" | "loading" | "ready" | "error";

interface StatusBarProps {
  phase: Phase;
  /** Free-text progress note, e.g. the elapsed-time hint. */
  message: string | null;
  error: string | null;
  /** Operator-facing detail from the API, shown collapsed. */
  detail?: string | null;
  provider: ProviderId | null;
  model: string | null;
}

export default function StatusBar({
  phase,
  message,
  error,
  detail,
  provider,
  model,
}: StatusBarProps) {
  if (phase === "error" && error) {
    return (
      <div
        role="alert"
        className="rounded-lg border border-rose-900 bg-rose-950/50 px-3 py-2.5"
      >
        <p className="flex items-start gap-2 text-sm font-medium text-rose-200">
          <svg
            viewBox="0 0 24 24"
            aria-hidden="true"
            className="mt-0.5 h-4 w-4 shrink-0"
            fill="none"
            stroke="currentColor"
            strokeWidth={2}
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M12 9v4m0 4h.01M10.3 3.9 1.8 18a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 3.9a2 2 0 0 0-3.4 0Z"
            />
          </svg>
          <span>{error}</span>
        </p>
        {detail && (
          <details className="mt-2">
            <summary className="cursor-pointer text-xs text-rose-400/80 hover:text-rose-300">
              Technical details
            </summary>
            <p className="mt-1 break-words text-xs leading-relaxed text-rose-300/70">
              {detail}
            </p>
          </details>
        )}
      </div>
    );
  }

  if (phase === "generating" || phase === "loading") {
    return (
      <div
        role="status"
        aria-live="polite"
        className="rounded-lg border border-sky-900/70 bg-sky-950/40 px-3 py-2.5"
      >
        <p className="flex items-center gap-2 text-sm font-medium text-sky-200">
          <span className="h-4 w-4 shrink-0 animate-spin rounded-full border-2 border-sky-800 border-t-sky-400" />
          {phase === "generating"
            ? "Generating 3D model… this can take 20–60s"
            : "Downloading model…"}
        </p>
        {message && (
          <p className="mt-1 pl-6 text-xs text-sky-300/70">{message}</p>
        )}
      </div>
    );
  }

  if (phase === "ready" && provider) {
    return (
      <div
        role="status"
        aria-live="polite"
        className="rounded-lg border border-emerald-900/70 bg-emerald-950/30 px-3 py-2.5"
      >
        <p className="flex items-center gap-2 text-sm font-medium text-emerald-200">
          <svg
            viewBox="0 0 24 24"
            aria-hidden="true"
            className="h-4 w-4 shrink-0"
            fill="none"
            stroke="currentColor"
            strokeWidth={2}
          >
            <path strokeLinecap="round" strokeLinejoin="round" d="m5 13 4 4L19 7" />
          </svg>
          Model ready
        </p>
        <p className="mt-1 pl-6 text-xs text-emerald-300/70">
          Generated by {PROVIDER_LABELS[provider]}
          {model ? ` · ${model}` : ""}
        </p>
      </div>
    );
  }

  return (
    <p className="rounded-lg border border-slate-800 bg-slate-900/50 px-3 py-2.5 text-xs text-slate-500">
      Models are generated by a free Hugging Face Space, so the first request
      after a quiet period may need a moment to warm up.
    </p>
  );
}
